### ISSUE TITLE
construction of init_values input file

### ISSUE THREAD

**Issue by DrLaurenCWhite** [fgvieira/ngsF#14]
Hi Felipe,
I was wondering if you could tell me how to construct the input file for --init_values?
I would like to use --fixed_freq and a list of MAF values that I previously estimated from a subset of my data. The total dataset contains a lot of close relatives which I think would skew the MAF estimates.  
Thanks a lot,
-Lauren

**Comment by fgvieira** [comment]
Hi Lauren,

the format of the input file for `--init_values` is the same as the output `.pars` file, namely a binary file with:
- global log-likelihood (1 double)
- per-individual log-likelihood (N_IND doubles)
- per-individual inbreeding coefficients (N_IND doubles)
- minor allele frequencies (N_SITES doubles)

since you are only interested on the MAF, you can just include dummy values for the other parameters (lkl and inbreeding).
Hope it makes sense. :smile:

**Comment by DrLaurenCWhite** [comment]
Thanks for your quick response!
Just to be clear, the file then contains just 4 lines?
Thanks again!

**Comment by fgvieira** [comment]
The file is binary, so there are no 'real' lines... but if you have 10 individuals and 1000 sites, your file will have 1021 doubles (1 + 10 + 10 + 1000)

**Comment by DrLaurenCWhite** [comment]
ah I see! Great, thanks again.
